### ISSUE TITLE
It gives check wifi error.

### ISSUE THREAD

**Issue by ghost** [Coolshanlan/Copy-Translator#1]
I downloaded and do eng->tr but it gives check wifi error (google)

**Comment by Coolshanlan** [comment]
Are you using Windows cause this project only supports Windows now.

**Comment by ghost** [comment]
Yes

**Comment by Coolshanlan** [comment]
OK, I fixed some bugs and add a debug message in the new version.
You can download again and if have any bug, please report to me with log message in the file of log.txt.

**Comment by ghost** [comment]
It works flawlessly, thanks!!! But I just did not understand a thing, I am trying to translate "dead word" it gives this result ```
形容詞:ölü,ölmüş,cansız,çıkmaz
副  詞:tamamen,aşırı,büsbütün
名  詞:ölü zaman
```

**Comment by ghost** [comment]
Bro, I could not understand why I got chinese stuff like that while translating eng.
形容詞: ölü, ölmüş, cansız, çıkmaz 副 詞: tamamen, aşırı, büsbütün 名 詞: ölü zaman

**Comment by Coolshanlan** [comment]
OK, I fixed this problem, please download again

**Comment by ghost** [comment]
Damn bro it is too good! Thanks for your hard working.
