### ISSUE TITLE
選取文字後，一直卡在Translating

### ISSUE THREAD

**Issue by h95332** [Coolshanlan/Copy-Translator#12]
正常使用超過半年，在某一次windowsupdate後就發生無法翻譯的情況
![螢幕擷取畫面 2023-11-28 164453](https://github.com/Coolshanlan/HighlightTranslator/assets/69151799/c3b2363a-8988-4536-97a3-8780073aaccc)

**Comment by Coolshanlan** [comment]
感謝你的回報，目前問題已經修復，[重新下載](https://coolshan.pse.is/3jrczc)即可

主要是在最近的 windows 更新中對 Virtual Desktop 進行改動，導致原本控制 Virtual Desktop 的 lib 失效，目前問題已經修復，若後續還有問題，再跟我說就可以了~

**Comment by h95332** [comment]
你好，Google雲端好像被砍掉了...

**Comment by Coolshanlan** [comment]
已修復，謝謝

**Comment by h95332** [comment]
沒問題了!!
謝謝
