### ISSUE TITLE
Question-Is there an embedded screenshot function?

### ISSUE THREAD

**Issue by andythebreaker** [Coolshanlan/Copy-Translator#6]
Since this program provides a screenshot translation function, I would like to ask whether the screenshot function has been embedded in the graphical user interface?
In more detail, I think if a button can be added and placed in the graphical user interface; after the user presses the "screenshot button", a cross cursor can be displayed so that the user can freely select random rectangular area of the screen, and take a screenshot of it, and then perform the translation action.
From my point of view, such a function can cope with embedded image text in some pdf files.

**Comment by Coolshanlan** [comment]
Hi @andythebreaker ,

Thank you for your feedback.
Actually I did consider this function before. However, now the sotfware only supports Windows system, which already has a pretty convenient keyboard shortcut `Windows + Shift + S`, so I didn't add this feature at the end.

Feel free to contact me for further questions or feedback!

**Comment by andythebreaker** [comment]
It sounds cool
This is a great software
Thank you for creating this tool

**Comment by Coolshanlan** [comment]
Glad to hear that! I would appreciate if you could share it to anyone who need it.
