### ISSUE TITLE
google drive 下載連結失效

### ISSUE THREAD

**Issue by andythebreaker** [Coolshanlan/Copy-Translator#9]
google drive下載連結(在markdown中)點進去之後是空的
猜應該是被google當作病毒了
![image](https://user-images.githubusercontent.com/43373581/160287449-53d1b334-6015-452d-8373-c5beb688bbea.png)

p.s.1:
FB是把這個東西直接當病毒拉QAQ

p.s.2:
這是備份的版本
https://filedoge.com/download/ba73f0bcc8597ce4b932ea68c2c55f7e511547800cffab8acfb63052dc45233db2ed92c968a0e6ebb4f0

**Comment by Coolshanlan** [comment]
感謝你的回報
我剛稍微測試了一下都可以下載也沒出現被擋掉的情形
你可以按按看螢幕右上方的下載按鈕(下圖中間) 試試看
<img width="95" alt="image" src="https://user-images.githubusercontent.com/40363835/160662156-7d48491c-f111-46b3-a690-12ad04640058.png">

如果還是無法下載，再麻煩您回報一下
感謝！

**Comment by andythebreaker** [comment]
你是對的
連結是活的
抱歉了
